### PR TITLE
Pursuit, LSP and documentation additions

### PR DESCRIPTION
**Pull request by postsolar**
Added:
1. Pursuit to "Essential Tools"
2. PureScript LSP to "Essential Tools"
3. A section "Documentation" with links to Jordan's PureScript Reference, PureScript by Example and PureScript Cookbook

### CODE REVIEW

**Review by sigma-andex — APPROVED** [review]
lgtm

**Comment by sigma-andex** [comment]
Can you fix 2. & 3. of the linting issues?

**Comment by postsolar** [comment]
Done 

> Can you fix 2. & 3. of the linting issues?

Done 👌

**Comment by postsolar** [comment]
> Can you fix 2. & 3. of the linting issues?

Done 👌

**Comment by sigma-andex** [comment]
Thx!

**Pull request merged**
